import type { AoiGroup, AreaOfInterest } from "@/domain/aoi";

export const AOI_GROUP_LABELS: Record<AoiGroup, string> = {
  case: "Кейс · Чёрное море, рейс DOORS 2024",
  reference: "Эталонные участки",
  "russian-seas": "Моря России",
};

export const AREAS_OF_INTEREST = [
  {
    id: "doors-west",
    name: "Разрезы T1–T2",
    seaName: "Чёрное море, западная часть",
    country: "рейс DOORS · 2 июня 2024",
    group: "case",
    center: [29.73, 43.58],
    zoom: 10.8,
    bbox: [29.55, 43.49, 29.91, 43.67],
    sentinel2Tiles: ["35TQJ"],
    rationale: "Визуальный учёт плавающего мусора > 2,5 см с судна; снимок Sentinel-2 в день учёта",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [29.85, 43.64], rank: "major" }],
    survey: {
      source: "S4 · DOORS3",
      target: "litter-visual",
      dates: ["2024-06-02"],
      period: ["2024-05-18", "2024-06-17"],
      events: ["T1", "T2"],
    },
  },
  {
    id: "doors-central",
    name: "Разрезы T30–T32",
    seaName: "Чёрное море, западная котловина",
    country: "рейс DOORS · 17 июня 2024",
    group: "case",
    center: [31.23, 42.49],
    zoom: 10.1,
    bbox: [30.88, 42.4, 31.58, 42.58],
    sentinel2Tiles: ["36TUN"],
    rationale: "Три разреза подряд в открытом море; пара с Sentinel-2B в день учёта",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [31.45, 42.42], rank: "major" }],
    survey: {
      source: "S4 · DOORS3",
      target: "litter-visual",
      dates: ["2024-06-17"],
      period: ["2024-06-02", "2024-07-02"],
      events: ["T30", "T31", "T32"],
    },
  },
  {
    id: "doors-batumi-north",
    name: "Разрезы T18–T19",
    seaName: "Чёрное море, юго-восточная часть",
    country: "рейс DOORS · 5 июня 2024",
    group: "case",
    center: [41.15, 41.78],
    zoom: 10.8,
    bbox: [40.95, 41.68, 41.35, 41.88],
    sentinel2Tiles: ["37TFG"],
    rationale: "Два разреза в открытом море к северо-западу от Батуми; пара с Sentinel-2B",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [41.2, 41.72], rank: "major" }],
    survey: {
      source: "S4 · DOORS3",
      target: "litter-visual",
      dates: ["2024-06-05"],
      period: ["2024-05-22", "2024-06-19"],
      events: ["T18", "T19"],
    },
  },
  {
    id: "doors-batumi",
    name: "Разрезы T20–T21",
    seaName: "Чёрное море у Батуми",
    country: "рейс DOORS · 7 июня 2024",
    group: "case",
    center: [41.6, 41.66],
    zoom: 11.1,
    bbox: [41.45, 41.52, 41.75, 41.8],
    sentinel2Tiles: ["37TGG"],
    rationale: "Прибрежные разрезы у Батуми: сток рек и порт; пара с Sentinel-2A",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [41.52, 41.7], rank: "major" }],
    survey: {
      source: "S4 · DOORS3",
      target: "litter-visual",
      dates: ["2024-06-07"],
      period: ["2024-05-24", "2024-06-21"],
      events: ["T20", "T21"],
    },
  },
  {
    id: "gulf-of-honduras",
    name: "Гондурасский залив",
    seaName: "Карибское море",
    country: "Гондурас · Гватемала · Белиз",
    group: "reference",
    center: [-88.34, 15.92],
    zoom: 10.3,
    bbox: [-88.72, 15.72, -87.96, 16.12],
    sentinel2Tiles: ["16PCC", "16PDC", "16PEC", "16QED"],
    rationale:
      "Наиболее полно размеченный участок MARIDA: выносы мусора рекой Мотагуа после паводков",
    datasets: ["marida", "mados", "nasa-marine-debris"],
    waterLabels: [
      { name: "Гондурасский залив", position: [-88.3, 15.94], rank: "major" },
      { name: "бухта Омоа", position: [-88.12, 15.79], rank: "minor", minZoom: 9 },
      { name: "залив Аматике", position: [-88.64, 15.8], rank: "minor", minZoom: 9 },
    ],
    reference: { date: "2020-09-18", period: ["2020-09-01", "2020-10-15"] },
  },
  {
    id: "gulf-of-gera",
    name: "Залив Гера, Лесбос",
    seaName: "Эгейское море",
    country: "Греция",
    group: "reference",
    center: [26.47, 39.06],
    zoom: 11.6,
    bbox: [26.36, 38.98, 26.58, 39.13],
    sentinel2Tiles: ["35SMD"],
    rationale:
      "Полигон Plastic Litter Project: контрольные мишени из HDPE и дерева известной площади",
    datasets: ["plp2021", "plp2022-2023"],
    waterLabels: [{ name: "залив Гера", position: [26.475, 39.085], rank: "major" }],
  },
  {
    id: "durban",
    name: "Дурбан",
    seaName: "Индийский океан",
    country: "ЮАР",
    group: "reference",
    center: [31.06, -29.88],
    zoom: 10.8,
    bbox: [30.85, -30.05, 31.25, -29.7],
    sentinel2Tiles: [],
    rationale: "Выносы мусора после паводков; отдельный тестовый набор в marinedebrisdetector",
    datasets: ["marida", "marinedebrisdetector"],
    waterLabels: [{ name: "Индийский океан", position: [31.16, -29.93], rank: "major" }],
  },
  {
    id: "novorossiysk",
    name: "Новороссийск",
    seaName: "Чёрное море, Цемесская бухта",
    country: "Россия",
    group: "russian-seas",
    center: [37.873, 44.69],
    zoom: 11,
    bbox: [37.7466, 44.6, 37.9998, 44.78],
    sentinel2Tiles: ["37TDK"],
    rationale: "Крупнейший порт на Чёрном море, нефтеналивные терминалы",
    datasets: [],
    waterLabels: [
      { name: "Цемесская бухта", position: [37.845, 44.672], rank: "major" },
      { name: "Чёрное море", position: [37.79, 44.615], rank: "minor" },
    ],
  },
  {
    id: "anapa",
    name: "Анапа",
    seaName: "Чёрное море, Анапа — Благовещенская",
    country: "Россия",
    group: "russian-seas",
    center: [37.23, 44.96],
    zoom: 10.9,
    bbox: [37.0887, 44.86, 37.3713, 45.06],
    sentinel2Tiles: ["37TCK"],
    rationale: "Пляжная зона; разлив мазута в декабре 2024",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [37.16, 44.93], rank: "major" }],
  },
  {
    id: "kerch-strait",
    name: "Керченский пролив",
    seaName: "Азовское и Чёрное моря",
    country: "Россия",
    group: "russian-seas",
    center: [36.56, 45.26],
    zoom: 10.4,
    bbox: [36.3611, 45.12, 36.7589, 45.4],
    sentinel2Tiles: ["36TYR"],
    rationale: "Водообмен Азовского и Чёрного морей, интенсивное судоходство",
    datasets: [],
    waterLabels: [{ name: "Керченский пролив", position: [36.58, 45.3], rank: "major" }],
  },
  {
    id: "tuapse",
    name: "Туапсе",
    seaName: "Чёрное море",
    country: "Россия",
    group: "russian-seas",
    center: [39.12, 44.09],
    zoom: 11.2,
    bbox: [39.0086, 44.01, 39.2314, 44.17],
    sentinel2Tiles: ["37TEJ"],
    rationale: "Порт и нефтеналивной терминал, устье р. Туапсе",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [39.05, 44.04], rank: "major" }],
  },
  {
    id: "sochi",
    name: "Сочи — Адлер",
    seaName: "Чёрное море",
    country: "Россия",
    group: "russian-seas",
    center: [39.8, 43.52],
    zoom: 10.9,
    bbox: [39.6621, 43.42, 39.9379, 43.62],
    sentinel2Tiles: ["37TEJ"],
    rationale: "Курортное побережье, устья рек Сочи и Мзымты",
    datasets: [],
    waterLabels: [{ name: "Чёрное море", position: [39.72, 43.46], rank: "major" }],
  },
  {
    id: "don-delta",
    name: "Таганрогский залив",
    seaName: "Азовское море, дельта Дона",
    country: "Россия",
    group: "russian-seas",
    center: [39.153, 47.15],
    zoom: 10.8,
    bbox: [39.0058, 47.05, 39.2998, 47.25],
    sentinel2Tiles: ["37TEN"],
    rationale: "Вынос Дона; порты Ростов-на-Дону, Азов, Таганрог",
    datasets: [],
    waterLabels: [{ name: "Таганрогский залив", position: [39.1, 47.16], rank: "major" }],
  },
  {
    id: "kuban-mouth",
    name: "Темрюкский залив",
    seaName: "Азовское море, устье Кубани",
    country: "Россия",
    group: "russian-seas",
    center: [37.36, 45.36],
    zoom: 11.1,
    bbox: [37.2461, 45.28, 37.4739, 45.44],
    sentinel2Tiles: ["37TCL"],
    rationale: "Вынос Кубани, порт Темрюк",
    datasets: [],
    waterLabels: [{ name: "Темрюкский залив", position: [37.34, 45.38], rank: "major" }],
  },
  {
    id: "yeysk",
    name: "Ейск",
    seaName: "Азовское море",
    country: "Россия",
    group: "russian-seas",
    center: [38.25, 46.72],
    zoom: 11.3,
    bbox: [38.1479, 46.65, 38.3521, 46.79],
    sentinel2Tiles: ["37TDM"],
    rationale: "Порт и Ейский лиман",
    datasets: [],
    waterLabels: [
      { name: "Таганрогский залив", position: [38.2, 46.76], rank: "major" },
      { name: "Ейский лиман", position: [38.33, 46.69], rank: "minor", minZoom: 10 },
    ],
  },
  {
    id: "neva-bay",
    name: "Невская губа",
    seaName: "Финский залив, Балтийское море",
    country: "Россия",
    group: "russian-seas",
    center: [29.85, 59.95],
    zoom: 10,
    bbox: [29.4, 59.8, 30.3, 60.1],
    sentinel2Tiles: [],
    rationale: "Сток Невы и городская агломерация; модель течений BALTICSEA ~1,85 км",
    datasets: [],
    waterLabels: [
      { name: "Невская губа", position: [30.06, 59.94], rank: "major" },
      { name: "Финский залив", position: [29.52, 60.0], rank: "minor" },
    ],
  },
  {
    id: "peter-the-great-bay",
    name: "Амурский залив",
    seaName: "Японское море",
    country: "Россия",
    group: "russian-seas",
    center: [131.85, 43.12],
    zoom: 10,
    bbox: [131.5, 42.9, 132.2, 43.35],
    sentinel2Tiles: [],
    rationale: "Залив Петра Великого у Владивостока: сток рек и портовая активность",
    datasets: [],
    waterLabels: [
      { name: "Амурский залив", position: [131.8, 43.18], rank: "major" },
      { name: "Уссурийский залив", position: [132.12, 43.08], rank: "minor" },
    ],
  },
] as const satisfies readonly AreaOfInterest[];

export type AoiId = (typeof AREAS_OF_INTEREST)[number]["id"];

export const DEFAULT_AOI_ID: AoiId = "doors-west";

export const DEMO_AOI: AoiId = "gulf-of-honduras";

export function findAoi(id: string): AreaOfInterest | undefined {
  return AREAS_OF_INTEREST.find((aoi) => aoi.id === id);
}
